set_property IOSTANDARD LVCMOS33 [get_ports {seg_ctrl[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ctrl[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ctrl[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ctrl[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ctrl[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ctrl[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ctrl[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ctrl[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[0]}]
set_property PACKAGE_PIN U13 [get_ports {seg_ctrl[7]}]
set_property PACKAGE_PIN K2 [get_ports {seg_ctrl[6]}]
set_property PACKAGE_PIN T14 [get_ports {seg_ctrl[5]}]
set_property PACKAGE_PIN P14 [get_ports {seg_ctrl[4]}]
set_property PACKAGE_PIN J14 [get_ports {seg_ctrl[3]}]
set_property PACKAGE_PIN T9 [get_ports {seg_ctrl[2]}]
set_property PACKAGE_PIN J18 [get_ports {seg_ctrl[1]}]
set_property PACKAGE_PIN J17 [get_ports {seg_ctrl[0]}]
set_property PACKAGE_PIN T10 [get_ports {seg_out[6]}]

set_property PACKAGE_PIN R10 [get_ports {seg_out[5]}]
set_property PACKAGE_PIN K16 [get_ports {seg_out[4]}]
set_property PACKAGE_PIN P15 [get_ports {seg_out[2]}]
set_property PACKAGE_PIN T11 [get_ports {seg_out[1]}]
set_property PACKAGE_PIN L18 [get_ports {seg_out[0]}]
set_property PACKAGE_PIN K13 [get_ports {seg_out[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN V11 [get_ports {led[15]}]
set_property PACKAGE_PIN V12 [get_ports {led[14]}]
set_property PACKAGE_PIN V14 [get_ports {led[13]}]
set_property PACKAGE_PIN V15 [get_ports {led[12]}]
set_property PACKAGE_PIN T16 [get_ports {led[11]}]
set_property PACKAGE_PIN U14 [get_ports {led[10]}]
set_property PACKAGE_PIN T15 [get_ports {led[9]}]
set_property PACKAGE_PIN V16 [get_ports {led[8]}]
set_property PACKAGE_PIN U16 [get_ports {led[7]}]
set_property PACKAGE_PIN U17 [get_ports {led[6]}]
set_property PACKAGE_PIN V17 [get_ports {led[5]}]
set_property PACKAGE_PIN R18 [get_ports {led[4]}]
set_property PACKAGE_PIN N14 [get_ports {led[3]}]
set_property PACKAGE_PIN J13 [get_ports {led[2]}]
set_property PACKAGE_PIN K15 [get_ports {led[1]}]
set_property PACKAGE_PIN H17 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]
set_property PACKAGE_PIN D8 [get_ports {VGA_B[3]}]
set_property PACKAGE_PIN D7 [get_ports {VGA_B[2]}]
set_property PACKAGE_PIN C7 [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN B7 [get_ports {VGA_B[0]}]
set_property PACKAGE_PIN A6 [get_ports {VGA_G[3]}]
set_property PACKAGE_PIN B6 [get_ports {VGA_G[2]}]
set_property PACKAGE_PIN A5 [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN C6 [get_ports {VGA_G[0]}]
set_property PACKAGE_PIN A4 [get_ports {VGA_R[3]}]
set_property PACKAGE_PIN C5 [get_ports {VGA_R[2]}]
set_property PACKAGE_PIN B4 [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN A3 [get_ports {VGA_R[0]}]
set_property PACKAGE_PIN E3 [get_ports clk_in1]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in1]
set_property IOSTANDARD LVCMOS33 [get_ports reset_button]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_HS]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_VS]
set_property PACKAGE_PIN B11 [get_ports VGA_HS]
set_property PACKAGE_PIN B12 [get_ports VGA_VS]
set_property PACKAGE_PIN V10 [get_ports reset_button]
set_property IOSTANDARD LVCMOS33 [get_ports manual_clk]
set_property PACKAGE_PIN P18 [get_ports manual_clk]
# set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets manual_clk_IBUF]

set_property IOSTANDARD LVCMOS33 [get_ports {debug_sel[0]}]
set_property PACKAGE_PIN R16 [get_ports {debug_sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_sel[1]}]
set_property PACKAGE_PIN T13 [get_ports {debug_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_sel[2]}]
set_property PACKAGE_PIN H6 [get_ports {debug_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_sel[3]}]
set_property PACKAGE_PIN U12 [get_ports {debug_sel[3]}]

set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {SW[0]}]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports {SW[1]}]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports {SW[2]}]
set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS33} [get_ports {SW[3]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {SW[4]}]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports {SW[5]}]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {SW[6]}]
set_property -dict {PACKAGE_PIN R13 IOSTANDARD LVCMOS33} [get_ports {SW[7]}]

set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33} [get_ports PS2_CLK]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33} [get_ports PS2_DATA]

#Quad SPI Flash
#Bank = CONFIG, Pin name = CCLK_0,              Sch name = QSPI_SCK
#set_property PACKAGE_PIN E9 [get_ports {flash_c}]
# set_property IOSTANDARD LVCMOS33 [get_ports {flash_c}]
#Bank = CONFIG, Pin name = IO_L1P_T0_D00_MOSI_14,     Sch name = QSPI_DQ0
set_property PACKAGE_PIN K17 [get_ports {flash_dq[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flash_dq[0]}]
#Bank = CONFIG, Pin name = IO_L1N_T0_D01_DIN_14,      Sch name = QSPI_DQ1
set_property PACKAGE_PIN K18 [get_ports {flash_dq[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flash_dq[1]}]
#Bank = CONFIG, Pin name = IO_L20_T0_D02_14,        Sch name = QSPI_DQ2
set_property PACKAGE_PIN L14 [get_ports {flash_dq[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flash_dq[2]}]
#Bank = CONFIG, Pin name = IO_L2P_T0_D03_14,        Sch name = QSPI_DQ3
set_property PACKAGE_PIN M14 [get_ports {flash_dq[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flash_dq[3]}]
#Bank = CONFIG, Pin name = IO_L15N_T2_DQS_DOUT_CSO_B_14,  Sch name = QSPI_CSN
set_property PACKAGE_PIN L13 [get_ports flash_s]
set_property IOSTANDARD LVCMOS33 [get_ports flash_s]


create_debug_core u_ila_0_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0_0]
set_property port_width 1 [get_debug_ports u_ila_0_0/clk]
connect_debug_port u_ila_0_0/clk [get_nets [list clk_BUFG]]
set_property port_width 32 [get_debug_ports u_ila_0_0/probe0]
connect_debug_port u_ila_0_0/probe0 [get_nets [list {inst_ci/instr_data_out[0]} {inst_ci/instr_data_out[1]} {inst_ci/instr_data_out[2]} {inst_ci/instr_data_out[3]} {inst_ci/instr_data_out[4]} {inst_ci/instr_data_out[5]} {inst_ci/instr_data_out[6]} {inst_ci/instr_data_out[7]} {inst_ci/instr_data_out[8]} {inst_ci/instr_data_out[9]} {inst_ci/instr_data_out[10]} {inst_ci/instr_data_out[11]} {inst_ci/instr_data_out[12]} {inst_ci/instr_data_out[13]} {inst_ci/instr_data_out[14]} {inst_ci/instr_data_out[15]} {inst_ci/instr_data_out[16]} {inst_ci/instr_data_out[17]} {inst_ci/instr_data_out[18]} {inst_ci/instr_data_out[19]} {inst_ci/instr_data_out[20]} {inst_ci/instr_data_out[21]} {inst_ci/instr_data_out[22]} {inst_ci/instr_data_out[23]} {inst_ci/instr_data_out[24]} {inst_ci/instr_data_out[25]} {inst_ci/instr_data_out[26]} {inst_ci/instr_data_out[27]} {inst_ci/instr_data_out[28]} {inst_ci/instr_data_out[29]} {inst_ci/instr_data_out[30]} {inst_ci/instr_data_out[31]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list inst_ci/ddr_ctrl_0/m70/u_mig_7series_0_mig/u_ddr2_infrastructure/CLK]]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list clk]]
create_debug_port u_ila_0_0 probe
set_property port_width 32 [get_debug_ports u_ila_0_0/probe1]
connect_debug_port u_ila_0_0/probe1 [get_nets [list {inst_ci/dmem_data_out[0]} {inst_ci/dmem_data_out[1]} {inst_ci/dmem_data_out[2]} {inst_ci/dmem_data_out[3]} {inst_ci/dmem_data_out[4]} {inst_ci/dmem_data_out[5]} {inst_ci/dmem_data_out[6]} {inst_ci/dmem_data_out[7]} {inst_ci/dmem_data_out[8]} {inst_ci/dmem_data_out[9]} {inst_ci/dmem_data_out[10]} {inst_ci/dmem_data_out[11]} {inst_ci/dmem_data_out[12]} {inst_ci/dmem_data_out[13]} {inst_ci/dmem_data_out[14]} {inst_ci/dmem_data_out[15]} {inst_ci/dmem_data_out[16]} {inst_ci/dmem_data_out[17]} {inst_ci/dmem_data_out[18]} {inst_ci/dmem_data_out[19]} {inst_ci/dmem_data_out[20]} {inst_ci/dmem_data_out[21]} {inst_ci/dmem_data_out[22]} {inst_ci/dmem_data_out[23]} {inst_ci/dmem_data_out[24]} {inst_ci/dmem_data_out[25]} {inst_ci/dmem_data_out[26]} {inst_ci/dmem_data_out[27]} {inst_ci/dmem_data_out[28]} {inst_ci/dmem_data_out[29]} {inst_ci/dmem_data_out[30]} {inst_ci/dmem_data_out[31]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 32 [get_debug_ports u_ila_0_0/probe2]
connect_debug_port u_ila_0_0/probe2 [get_nets [list {mem_alu_res[0]} {mem_alu_res[1]} {mem_alu_res[2]} {mem_alu_res[3]} {mem_alu_res[4]} {mem_alu_res[5]} {mem_alu_res[6]} {mem_alu_res[7]} {mem_alu_res[8]} {mem_alu_res[9]} {mem_alu_res[10]} {mem_alu_res[11]} {mem_alu_res[12]} {mem_alu_res[13]} {mem_alu_res[14]} {mem_alu_res[15]} {mem_alu_res[16]} {mem_alu_res[17]} {mem_alu_res[18]} {mem_alu_res[19]} {mem_alu_res[20]} {mem_alu_res[21]} {mem_alu_res[22]} {mem_alu_res[23]} {mem_alu_res[24]} {mem_alu_res[25]} {mem_alu_res[26]} {mem_alu_res[27]} {mem_alu_res[28]} {mem_alu_res[29]} {mem_alu_res[30]} {mem_alu_res[31]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 32 [get_debug_ports u_ila_0_0/probe3]
connect_debug_port u_ila_0_0/probe3 [get_nets [list {mem_pc[0]} {mem_pc[1]} {mem_pc[2]} {mem_pc[3]} {mem_pc[4]} {mem_pc[5]} {mem_pc[6]} {mem_pc[7]} {mem_pc[8]} {mem_pc[9]} {mem_pc[10]} {mem_pc[11]} {mem_pc[12]} {mem_pc[13]} {mem_pc[14]} {mem_pc[15]} {mem_pc[16]} {mem_pc[17]} {mem_pc[18]} {mem_pc[19]} {mem_pc[20]} {mem_pc[21]} {mem_pc[22]} {mem_pc[23]} {mem_pc[24]} {mem_pc[25]} {mem_pc[26]} {mem_pc[27]} {mem_pc[28]} {mem_pc[29]} {mem_pc[30]} {mem_pc[31]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 32 [get_debug_ports u_ila_0_0/probe4]
connect_debug_port u_ila_0_0/probe4 [get_nets [list {mem_data[0]} {mem_data[1]} {mem_data[2]} {mem_data[3]} {mem_data[4]} {mem_data[5]} {mem_data[6]} {mem_data[7]} {mem_data[8]} {mem_data[9]} {mem_data[10]} {mem_data[11]} {mem_data[12]} {mem_data[13]} {mem_data[14]} {mem_data[15]} {mem_data[16]} {mem_data[17]} {mem_data[18]} {mem_data[19]} {mem_data[20]} {mem_data[21]} {mem_data[22]} {mem_data[23]} {mem_data[24]} {mem_data[25]} {mem_data[26]} {mem_data[27]} {mem_data[28]} {mem_data[29]} {mem_data[30]} {mem_data[31]}]]
create_debug_port u_ila_0_0 probe
set_property port_width 1 [get_debug_ports u_ila_0_0/probe5]
connect_debug_port u_ila_0_0/probe5 [get_nets [list inst_ci/kb_cpu_read]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_BUFG]

set_property -dict {PACKAGE_PIN T8 IOSTANDARD LVCMOS18} [get_ports {CLK_SEL[0]}]
set_property -dict {PACKAGE_PIN U8 IOSTANDARD LVCMOS18} [get_ports {CLK_SEL[1]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets BP_SAMPLER_IBUF]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports BP_SAMPLER]
set_property -dict {PACKAGE_PIN U11 IOSTANDARD LVCMOS33} [get_ports BP_VALID]

