set_property IOSTANDARD LVCMOS33 [get_ports {seg_ctrl[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ctrl[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ctrl[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ctrl[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ctrl[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ctrl[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ctrl[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_ctrl[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[0]}]
set_property PACKAGE_PIN U13 [get_ports {seg_ctrl[7]}]
set_property PACKAGE_PIN K2 [get_ports {seg_ctrl[6]}]
set_property PACKAGE_PIN T14 [get_ports {seg_ctrl[5]}]
set_property PACKAGE_PIN P14 [get_ports {seg_ctrl[4]}]
set_property PACKAGE_PIN J14 [get_ports {seg_ctrl[3]}]
set_property PACKAGE_PIN T9 [get_ports {seg_ctrl[2]}]
set_property PACKAGE_PIN J18 [get_ports {seg_ctrl[1]}]
set_property PACKAGE_PIN J17 [get_ports {seg_ctrl[0]}]
set_property PACKAGE_PIN T10 [get_ports {seg_out[6]}]

set_property PACKAGE_PIN R10 [get_ports {seg_out[5]}]
set_property PACKAGE_PIN K16 [get_ports {seg_out[4]}]
set_property PACKAGE_PIN P15 [get_ports {seg_out[2]}]
set_property PACKAGE_PIN T11 [get_ports {seg_out[1]}]
set_property PACKAGE_PIN L18 [get_ports {seg_out[0]}]
set_property PACKAGE_PIN K13 [get_ports {seg_out[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN V11 [get_ports {led[15]}]
set_property PACKAGE_PIN V12 [get_ports {led[14]}]
set_property PACKAGE_PIN V14 [get_ports {led[13]}]
set_property PACKAGE_PIN V15 [get_ports {led[12]}]
set_property PACKAGE_PIN T16 [get_ports {led[11]}]
set_property PACKAGE_PIN U14 [get_ports {led[10]}]
set_property PACKAGE_PIN T15 [get_ports {led[9]}]
set_property PACKAGE_PIN V16 [get_ports {led[8]}]
set_property PACKAGE_PIN U16 [get_ports {led[7]}]
set_property PACKAGE_PIN U17 [get_ports {led[6]}]
set_property PACKAGE_PIN V17 [get_ports {led[5]}]
set_property PACKAGE_PIN R18 [get_ports {led[4]}]
set_property PACKAGE_PIN N14 [get_ports {led[3]}]
set_property PACKAGE_PIN J13 [get_ports {led[2]}]
set_property PACKAGE_PIN K15 [get_ports {led[1]}]
set_property PACKAGE_PIN H17 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]
set_property PACKAGE_PIN D8 [get_ports {VGA_B[3]}]
set_property PACKAGE_PIN D7 [get_ports {VGA_B[2]}]
set_property PACKAGE_PIN C7 [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN B7 [get_ports {VGA_B[0]}]
set_property PACKAGE_PIN A6 [get_ports {VGA_G[3]}]
set_property PACKAGE_PIN B6 [get_ports {VGA_G[2]}]
set_property PACKAGE_PIN A5 [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN C6 [get_ports {VGA_G[0]}]
set_property PACKAGE_PIN A4 [get_ports {VGA_R[3]}]
set_property PACKAGE_PIN C5 [get_ports {VGA_R[2]}]
set_property PACKAGE_PIN B4 [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN A3 [get_ports {VGA_R[0]}]
set_property PACKAGE_PIN E3 [get_ports clk_in1]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in1]
set_property IOSTANDARD LVCMOS33 [get_ports reset_button]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_HS]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_VS]
set_property PACKAGE_PIN B11 [get_ports VGA_HS]
set_property PACKAGE_PIN B12 [get_ports VGA_VS]
set_property PACKAGE_PIN V10 [get_ports reset_button]
set_property IOSTANDARD LVCMOS33 [get_ports manual_clk]
set_property PACKAGE_PIN P18 [get_ports manual_clk]
# set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets manual_clk_IBUF]

set_property IOSTANDARD LVCMOS33 [get_ports {debug_sel[0]}]
set_property PACKAGE_PIN R16 [get_ports {debug_sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_sel[1]}]
set_property PACKAGE_PIN T13 [get_ports {debug_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_sel[2]}]
set_property PACKAGE_PIN H6 [get_ports {debug_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_sel[3]}]
set_property PACKAGE_PIN U12 [get_ports {debug_sel[3]}]

set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {SW[0]}]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports {SW[1]}]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports {SW[2]}]
set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS33} [get_ports {SW[3]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {SW[4]}]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports {SW[5]}]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {SW[6]}]
set_property -dict {PACKAGE_PIN R13 IOSTANDARD LVCMOS33} [get_ports {SW[7]}]

set_property -dict { PACKAGE_PIN F4    IOSTANDARD LVCMOS33 } [get_ports { PS2_CLK }]; #IO_L13P_T2_MRCC_35 Sch=ps2_clk
set_property -dict { PACKAGE_PIN B2    IOSTANDARD LVCMOS33 } [get_ports { PS2_DATA }]; #IO_L10N_T1_AD15N_35 Sch=ps2_data

#Quad SPI Flash
#Bank = CONFIG, Pin name = CCLK_0,              Sch name = QSPI_SCK
#set_property PACKAGE_PIN E9 [get_ports {flash_c}]
# set_property IOSTANDARD LVCMOS33 [get_ports {flash_c}]
#Bank = CONFIG, Pin name = IO_L1P_T0_D00_MOSI_14,     Sch name = QSPI_DQ0
set_property PACKAGE_PIN K17 [get_ports {flash_dq[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flash_dq[0]}]
#Bank = CONFIG, Pin name = IO_L1N_T0_D01_DIN_14,      Sch name = QSPI_DQ1
set_property PACKAGE_PIN K18 [get_ports {flash_dq[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flash_dq[1]}]
#Bank = CONFIG, Pin name = IO_L20_T0_D02_14,        Sch name = QSPI_DQ2
set_property PACKAGE_PIN L14 [get_ports {flash_dq[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flash_dq[2]}]
#Bank = CONFIG, Pin name = IO_L2P_T0_D03_14,        Sch name = QSPI_DQ3
set_property PACKAGE_PIN M14 [get_ports {flash_dq[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flash_dq[3]}]
#Bank = CONFIG, Pin name = IO_L15N_T2_DQS_DOUT_CSO_B_14,  Sch name = QSPI_CSN
set_property PACKAGE_PIN L13 [get_ports flash_s]
set_property IOSTANDARD LVCMOS33 [get_ports flash_s]
